import { StoneLocationData } from "../declarations";

export const STONE_LIST: StoneLocationData[] = [
    {
        stoneId: 0,
        locationName: 'Ansilvund',
        sublocationName: 'Ansilvund Burial Chambers',
        holdName: 'Eastmarch',
        stonePlacementDescription: 'Enter Ansilvund Excavation and complete the objective in the Ansilvund Burial Chambers, and it will be on the table in the back of the final room. Near the Ghostblade and Fjori\'s ghost.',
        stonePlacementImageFilename: '/assets/stonePlacement/ansilvund.png',
        stonePlacementImageAltText: 'Ansilvund Stone Location',
        locationImageFilename: 'https://static.wikia.nocookie.net/elderscrolls/images/4/4d/Ansilvund_Map2.jpg',
        locationImageAltText: 'Ansilvund Map',
    },
    {
        stoneId: 1,
        locationName: 'Stony Creek Cave',
        holdName: 'Eastmarch',
        stonePlacementDescription: 'Going off the main corridor, follow a path on the right (before entering the large pool of water with one bandit). It is inside the bandit wizard\'s cavern, on a table near an alchemy lab.',
        stonePlacementImageFilename: '/assets/stonePlacement/stony_creek_cave.png',
        stonePlacementImageAltText: 'Stony Creek Cave Stone Location',
        locationImageFilename: 'https://static.wikia.nocookie.net/elderscrolls/images/d/dd/StonyCreekCaveLocation.jpg',
        locationImageAltText: 'Stony Creek Cave Map',
    },
    {
        stoneId: 2,
        locationName: 'Windhelm',
        sublocationName: 'House of Clan Shatter-Shield',
        holdName: 'Eastmarch',
        stonePlacementDescription: 'Upstairs and in the first bedroom on the left, on the bookshelf.',
        stonePlacementImageFilename: '/assets/stonePlacement/windhelm_house_of_clan_shatter-shield.png',
        stonePlacementImageAltText: 'Windhelm, House of Clan Shatter-Shield Stone Location',
        locationImageFilename: 'https://static.wikia.nocookie.net/elderscrolls/images/6/65/House_of_Clan_Shatter-Shield_MapLocation.png',
        locationImageAltText: 'Windhelm, House of Clan Shatter-Shield Map',
    },
    {
        stoneId: 3,
        locationName: 'Windhelm',
        sublocationName: 'Palace of the Kings',
        holdName: 'Eastmarch',
        stonePlacementDescription: 'When entering the palace, take the first door to the left (upstairs) and follow the hall to the end. It sits on a table in Wuunferth the Unliving\'s quarters at the end of the hall.',
        stonePlacementImageFilename: '/assets/stonePlacement/windhelm_palace_of_the_kings.png',
        stonePlacementImageAltText: 'Windhelm, Palace of the Kings Stone Location',
        locationImageFilename: 'https://static.wikia.nocookie.net/elderscrolls/images/9/99/Palace_of_the_Kings_MapLocation.png',
        locationImageAltText: 'Windhelm, Palace of the Kings Map',
    },
    {
        stoneId: 4,
        locationName: 'Dark Brotherhood Sanctuary',
        holdName: 'Falkreath',
        stonePlacementDescription: 'On the dresser in Astrid\'s room during the quest "With Friends Like These..." or "Destroy the Dark Brotherhood!"',
        stonePlacementImageFilename: '/assets/stonePlacement/dark_brotherhood_sanctuary.png',
        stonePlacementImageAltText: 'Dark Brotherhood Sanctuary Stone Location',
        locationImageFilename: 'https://static.wikia.nocookie.net/elderscrolls/images/4/4d/Dark_Brotherhood_Sanctuary.jpg',
        locationImageAltText: 'Dark Brotherhood Sanctuary Map',
    },
    {
        stoneId: 5,
        locationName: 'Pinewatch',
        sublocationName: 'Bandit\'s Sanctuary',
        holdName: 'Falkreath',
        stonePlacementDescription: 'In a room containing a single bandit and several empty draugr sarcophagi, there is another small room (to the right, behind a locked door).\nThe stone is found on a shelf immediately on your right.',
        stonePlacementImageFilename: '/assets/stonePlacement/pinewatch.png',
        stonePlacementImageAltText: 'Pinewatch Stone Location',
        locationImageFilename: 'https://static.wikia.nocookie.net/elderscrolls/images/d/df/Skyrim_map_Pinewatch.jpg',
        locationImageAltText: 'Pinewatch Map',
    },
    {
        stoneId: 6,
        locationName: 'Sunderstone Gorge',
        holdName: 'Falkreath',
        stonePlacementDescription: 'On the altar in front of the Word Wall. Note that, because of its placement on the altar, the Stone can be difficult to spot if you are not facing the Word Wall from the opposite side of the table.',
        stonePlacementImageFilename: '/assets/stonePlacement/sunderstone_gorge.png',
        stonePlacementImageAltText: 'Sunderstone Gorge Stone Location',
        locationImageFilename: 'https://static.wikia.nocookie.net/elderscrolls/images/8/8d/Sunderstone_Gorge.png',
        locationImageAltText: 'Sunderstone Gorge Map',
    },
    {
        stoneId: 7,
        locationName: 'Dainty Sload',
        holdName: 'Haafingar',
        stonePlacementDescription: 'Take the stairs to the bottom level, take the stairs up (opposite the ones you have just come down). At the end of the room you will find the stone on the table.',
        stonePlacementImageFilename: '/assets/stonePlacement/dainty_sload.png',
        stonePlacementImageAltText: 'Dainty Sload Stone Location',
        locationImageFilename: 'https://static.wikia.nocookie.net/elderscrolls/images/9/9d/Dainty_Sload_Map.jpg',
        locationImageAltText: 'Dainty Sload Map',
    },
    {
        stoneId: 8,
        locationName: 'Reeking Cave',
        holdName: 'Haafingar',
        stonePlacementDescription: 'In the alcove with the dead conjurer near the road entrance.',
        stonePlacementImageFilename: '/assets/stonePlacement/reeking_cave.png',
        stonePlacementImageAltText: 'Reeking Cave Stone Location',
        locationImageFilename: 'https://static.wikia.nocookie.net/elderscrolls/images/3/3e/Reeking_Cave_Maplocation.png',
        locationImageAltText: 'Reeking Cave Map',
    },
    {
        stoneId: 9,
        locationName: 'Solitude',
        sublocationName: 'Blue Palace',
        holdName: 'Haafingar',
        stonePlacementDescription: 'On the bedside table in Jarl Elisif\'s quarters. Her room is at the end of the hallway forward and to the right-hand side, facing away from the throne.',
        stonePlacementImageFilename: '/assets/stonePlacement/solitude_blue_palace.png',
        stonePlacementImageAltText: 'Solitude, Blue Palace Stone Location',
        locationImageFilename: 'https://static.wikia.nocookie.net/elderscrolls/images/9/9f/Blue_Palace_Map.jpeg',
        locationImageAltText: 'Solitude, Blue Palace Map',
    },
    {
        stoneId: 10,
        locationName: 'Solitude',
        sublocationName: 'Proudspire Manor',
        holdName: 'Haafingar',
        stonePlacementDescription: 'Sitting on a chest of drawers on the left-hand side of the upstairs master bedroom. (Must own Proudspire Manor to get this stone. Requires paying 25,000 Gold to own.)',
        stonePlacementImageFilename: '/assets/stonePlacement/solitude_proudspire_manor.png',
        stonePlacementImageAltText: 'Solitude, Proudspire Manor Stone Location',
        locationImageFilename: 'https://static.wikia.nocookie.net/elderscrolls/images/7/7e/Proudspire_Manor_Map.png',
        locationImageAltText: 'Solitude, Proudspire Manor Map',
    },
    {
        stoneId: 11,
        locationName: 'Rannveig\'s Fast',
        holdName: 'Hjaalmarch',
        stonePlacementDescription: 'On a table just to the right of the prison\'s exit gate. The prison is entered via a trapdoor in front of the chest at the Word Wall, or long way through tunnels.',
        stonePlacementImageFilename: '/assets/stonePlacement/rannveigs_fast.png',
        stonePlacementImageAltText: 'Rannveig\'s Fast Stone Location',
        locationImageFilename: 'https://static.wikia.nocookie.net/elderscrolls/images/5/50/Skyrim_map_Rannveig%27s_Fast.jpg',
        locationImageAltText: 'Rannveig\'s Fast Map',
    },
    {
        stoneId: 12,
        locationName: 'Dead Crone Rock',
        holdName: 'The Reach',
        stonePlacementDescription: 'On a makeshift altar in front of the Word Wall at the top of the final tower.',
        stonePlacementImageFilename: '/assets/stonePlacement/dead_crone_rock.png',
        stonePlacementImageAltText: 'Dead Crone Rock Stone Location',
        locationImageFilename: 'https://static.wikia.nocookie.net/elderscrolls/images/7/77/Dead_Crone_Rock.jpg',
        locationImageAltText: 'Dead Crone Rock Map',
    },
    {
        stoneId: 13,
        locationName: 'Markarth',
        sublocationName: 'Treasury House',
        holdName: 'The Reach',
        stonePlacementDescription: 'Next to the bed in the master bedroom.',
        stonePlacementImageFilename: '/assets/stonePlacement/markarth.png',
        stonePlacementImageAltText: 'Markarth Stone Location',
        locationImageFilename: 'https://static.wikia.nocookie.net/elderscrolls/images/9/92/The_Treasury_House_map.png',
        locationImageAltText: 'Markarth Map',
    },
    {
        stoneId: 14,
        locationName: 'Understone Keep',
        sublocationName: 'Dwemer Museum',
        holdName: 'The Reach',
        stonePlacementDescription: 'Behind a locked gate on left of the museum on a table in the right hand corner.',
        stonePlacementImageFilename: '/assets/stonePlacement/understone_keep.png',
        stonePlacementImageAltText: 'Understone Keep Stone Location',
        locationImageFilename: 'https://static.wikia.nocookie.net/elderscrolls/images/a/aa/Understone_map.jpg',
        locationImageAltText: 'Understone Keep Map',
    },
    {
        stoneId: 15,
        locationName: 'Black-Briar Lodge',
        holdName: 'The Rift',
        stonePlacementDescription: 'On the left end table in the upstairs master bedroom.',
        stonePlacementImageFilename: '/assets/stonePlacement/black-briar_lodge.png',
        stonePlacementImageAltText: 'Black-Briar Lodge Stone Location',
        locationImageFilename: 'https://static.wikia.nocookie.net/elderscrolls/images/b/b3/Black-Briar_Lodge_World_Map_%28Skyrim%29.png',
        locationImageAltText: 'Black-Briar Lodge Map',
    },
    {
        stoneId: 16,
        locationName: 'Mistveil Keep',
        sublocationName: 'Jarl\'s Chambers',
        holdName: 'The Rift',
        stonePlacementDescription: 'In the Jarl\'s chambers, on the end table to the left of the bed in the master bedroom.',
        stonePlacementImageFilename: '/assets/stonePlacement/mistveil_keep.png',
        stonePlacementImageAltText: 'Mistveil Keep Stone Location',
        locationImageFilename: 'https://static.wikia.nocookie.net/elderscrolls/images/2/23/Mistveil_keep_location.jpg',
        locationImageAltText: 'Mistveil Keep Map',
    },
    {
        stoneId: 17,
        locationName: 'Dragonsreach',
        sublocationName: 'Jarl\'s Quarters',
        holdName: 'Whiterun',
        stonePlacementDescription: 'In the Jarl\'s chambers, on the end table to the right of the bed.',
        stonePlacementImageFilename: '/assets/stonePlacement/dragonsreach.png',
        stonePlacementImageAltText: 'Dragonsreach Stone Location',
        locationImageFilename: 'https://static.wikia.nocookie.net/elderscrolls/images/6/65/DRJarlsQtrsMap.png',
        locationImageAltText: 'Dragonsreach Map',
    },
    {
        stoneId: 18,
        locationName: 'Fellglow Keep',
        holdName: 'Whiterun',
        stonePlacementDescription: 'On a counter in the workshop at the top of the front foyer. It is between the arcane enchanter and the alchemy lab.',
        stonePlacementImageFilename: '/assets/stonePlacement/fellglow_keep.png',
        stonePlacementImageAltText: 'Fellglow Keep Stone Location',
        locationImageFilename: 'https://static.wikia.nocookie.net/elderscrolls/images/e/e0/Skyrim_map_Fellglow_Keep.jpg',
        locationImageAltText: 'Fellglow Keep Map',
    },
    {
        stoneId: 19,
        locationName: 'Jorrvaskr',
        sublocationName: 'Living Quarters',
        holdName: 'Whiterun',
        stonePlacementDescription: 'In Kodlak Whitemane\'s bedroom.',
        stonePlacementImageFilename: '/assets/stonePlacement/jorrvaskr.png',
        stonePlacementImageAltText: 'Jorrvaskr Stone Location',
        locationImageFilename: 'https://static.wikia.nocookie.net/elderscrolls/images/e/e9/Jorrvaskr_Skyrim_MapLocation.png',
        locationImageAltText: 'Jorrvaskr Map',
    },
    {
        stoneId: 20,
        locationName: 'Whiterun Hall of the Dead',
        sublocationName: 'Whiterun Catacombs',
        holdName: 'Whiterun',
        stonePlacementDescription: 'Found in a crypt. From the entrance make the first left, then right, down the ramp. From here it is on the immediate left.',
        stonePlacementImageFilename: '/assets/stonePlacement/whiterun_hall_of_the_dead.png',
        stonePlacementImageAltText: 'Whiterun Hall of the Dead Stone Location',
        locationImageFilename: 'https://static.wikia.nocookie.net/elderscrolls/images/a/a0/HODWhiterunmap.png',
        locationImageAltText: 'Whiterun Hall of the Dead Map',
    },
    {
        stoneId: 21,
        locationName: 'College of Winterhold',
        sublocationName: 'Arch-Mage\'s Quarters',
        holdName: 'Winterhold',
        stonePlacementDescription: 'On a shelf in the Arch-Mage\'s Quarters. To the left of the bed, under a wolf\'s head mounted on the wall. Becomes accessible during "Under Saarthal" when Tolfdir tells the Dragonborn to speak to the Arch-mage.',
        stonePlacementImageFilename: '/assets/stonePlacement/college_of_winterhold.png',
        stonePlacementImageAltText: 'College of Winterhold Stone Location',
        locationImageFilename: 'https://static.wikia.nocookie.net/elderscrolls/images/e/e2/College_of_winterhold_map.png',
        locationImageAltText: 'College of Winterhold Map',
    },
    {
        stoneId: 22,
        locationName: 'Hob\'s Fall Cave',
        holdName: 'Winterhold',
        stonePlacementDescription: 'After crossing the bridge, just before an area with a few impaled corpses and an arcane enchanter, take the path to the left and down into an area with an alchemy bench. The stone is on a shelf.',
        stonePlacementImageFilename: '/assets/stonePlacement/hobs_fall_cave.png',
        stonePlacementImageAltText: 'Hob\'s Fall Cave Stone Location',
        locationImageFilename: 'https://static.wikia.nocookie.net/elderscrolls/images/5/5f/HobsFallCave_Map.jpg',
        locationImageAltText: 'Hob\'s Fall Cave Map',
    },
    {
        stoneId: 23,
        locationName: 'Yngvild',
        sublocationName: 'Yngvild Throne Room',
        holdName: 'Winterhold',
        stonePlacementDescription: 'Found on the desk in the last room, next to the final journal of Arondil.',
        stonePlacementImageFilename: '/assets/stonePlacement/yngvild.png',
        stonePlacementImageAltText: 'Yngvild Stone Location',
        locationImageFilename: 'https://static.wikia.nocookie.net/elderscrolls/images/1/19/Yngvild_Map.jpg',
        locationImageAltText: 'Yngvild Map',
    },
]