import { StoneLocationData } from "../declarations";

export const STONE_LIST: StoneLocationData[] = [
    {
        stoneId: 0,
        locationName: 'Ansilvund',
        sublocationName: 'Ansilvund Burial Chambers',
        holdName: 'Eastmarch',
        stonePlacementDescription: 'Enter Ansilvund Excavation and complete the objective in the Ansilvund Burial Chambers, and it will be on the table in the back of the final room. Near the Ghostblade and Fjori\'s ghost.',
    },
    {
        stoneId: 1,
        locationName: 'Stony Creek Cave',
        holdName: 'Eastmarch',
        stonePlacementDescription: 'Going off the main corridor, follow a path on the right (before entering the large pool of water with one bandit). It is inside the bandit wizard\'s cavern, on a table near an alchemy lab.',
    },
    {
        stoneId: 2,
        locationName: 'Windhelm',
        sublocationName: 'House of Clan Shatter-Shield',
        holdName: 'Eastmarch',
        stonePlacementDescription: 'Upstairs and in the first bedroom on the left, on the bookshelf.',
    },
    {
        stoneId: 3,
        locationName: 'Windhelm',
        sublocationName: 'Palace of the Kings',
        holdName: 'Eastmarch',
        stonePlacementDescription: 'When entering the palace, take the first door to the left (upstairs) and follow the hall to the end. It sits on a table in Wuunferth the Unliving\'s quarters at the end of the hall.',
    },
    {
        stoneId: 4,
        locationName: 'Dark Brotherhood Sanctuary',
        holdName: 'Falkreath',
        stonePlacementDescription: 'On the dresser in Astrid\'s room during the quest "With Friends Like These..." or "Destroy the Dark Brotherhood!"',
    },
    {
        stoneId: 5,
        locationName: 'Pinewatch',
        sublocationName: 'Bandit\'s Sanctuary',
        holdName: 'Falkreath',
        stonePlacementDescription: 'In a room containing a single bandit and several empty draugr sarcophagi, there is another small room (to the right, behind a locked door).\nThe stone is found on a shelf immediately on your right.',
    },
    {
        stoneId: 6,
        locationName: 'Sunderstone Gorge',
        holdName: 'Falkreath',
        stonePlacementDescription: 'On the altar in front of the Word Wall. Note that, because of its placement on the altar, the Stone can be difficult to spot if you are not facing the Word Wall from the opposite side of the table.',
    },
    {
        stoneId: 7,
        locationName: 'Dainty Sload',
        holdName: 'Haafingar',
        stonePlacementDescription: 'Take the stairs to the bottom level, take the stairs up (opposite the ones you have just come down). At the end of the room you will find the stone on the table.',
    },
    {
        stoneId: 8,
        locationName: 'Reeking Cave',
        holdName: 'Haafingar',
        stonePlacementDescription: 'In the alcove with the dead conjurer near the road entrance.',
    },
    {
        stoneId: 9,
        locationName: 'Solitude',
        sublocationName: 'Blue Palace',
        holdName: 'Haafingar',
        stonePlacementDescription: 'On the bedside table in Jarl Elisif\'s quarters. Her room is at the end of the hallway forward and to the right-hand side, facing away from the throne.',
    },
    {
        stoneId: 10,
        locationName: 'Solitude',
        sublocationName: 'Proudspire Manor',
        holdName: 'Haafingar',
        stonePlacementDescription: 'Sitting on a chest of drawers on the left-hand side of the upstairs master bedroom. (Must own Proudspire Manor to get this stone. Requires paying 25,000 Gold to own.)',
    },
    {
        stoneId: 11,
        locationName: 'Rannveig\'s Fast',
        holdName: 'Hjaalmarch',
        stonePlacementDescription: 'On a table just to the right of the prison\'s exit gate. The prison is entered via a trapdoor in front of the chest at the Word Wall, or long way through tunnels.',
    },
    {
        stoneId: 12,
        locationName: 'Dead Crone Rock',
        holdName: 'The Reach',
        stonePlacementDescription: 'On a makeshift altar in front of the Word Wall at the top of the final tower.',
    },
    {
        stoneId: 13,
        locationName: 'Markarth',
        sublocationName: 'Treasury House',
        holdName: 'The Reach',
        stonePlacementDescription: 'Next to the bed in the master bedroom.',
    },
    {
        stoneId: 14,
        locationName: 'Understone Keep',
        sublocationName: 'Dwemer Museum',
        holdName: 'The Reach',
        stonePlacementDescription: 'Behind a locked gate on left of the museum on a table in the right hand corner.',
    },
    {
        stoneId: 15,
        locationName: 'Black-Briar Lodge',
        holdName: 'The Rift',
        stonePlacementDescription: 'On the left end table in the upstairs master bedroom.',
    },
    {
        stoneId: 16,
        locationName: 'Mistveil Keep',
        sublocationName: 'Jarl\'s Chambers',
        holdName: 'The Rift',
        stonePlacementDescription: 'In the Jarl\'s chambers, on the end table to the left of the bed in the master bedroom.',
    },
    {
        stoneId: 17,
        locationName: 'Dragonsreach',
        sublocationName: 'Jarl\'s Quarters',
        holdName: 'Whiterun',
        stonePlacementDescription: 'In the Jarl\'s chambers, on the end table to the right of the bed.',
    },
    {
        stoneId: 18,
        locationName: 'Fellglow Keep',
        holdName: 'Whiterun',
        stonePlacementDescription: 'On a counter in the workshop at the top of the front foyer. It is between the arcane enchanter and the alchemy lab.',
    },
    {
        stoneId: 19,
        locationName: 'Jorrvaskr',
        sublocationName: 'Living Quarters',
        holdName: 'Whiterun',
        stonePlacementDescription: 'In Kodlak Whitemane\'s bedroom.',
    },
    {
        stoneId: 20,
        locationName: 'Whiterun Hall of the Dead',
        sublocationName: 'Whiterun Catacombs',
        holdName: 'Whiterun',
        stonePlacementDescription: 'Found in a crypt. From the entrance make the first left, then right, down the ramp. From here it is on the immediate left.',
    },
    {
        stoneId: 21,
        locationName: 'College of Winterhold',
        sublocationName: 'Arch-Mage\'s Quarters',
        holdName: 'Winterhold',
        stonePlacementDescription: 'On a shelf in the Arch-Mage\'s Quarters. To the left of the bed, under a wolf\'s head mounted on the wall. Becomes accessible during "Under Saarthal" when Tolfdir tells the Dragonborn to speak to the Arch-mage.',
    },
    {
        stoneId: 22,
        locationName: 'Hob\'s Fall Cave',
        holdName: 'Winterhold',
        stonePlacementDescription: 'After crossing the bridge, just before an area with a few impaled corpses and an arcane enchanter, take the path to the left and down into an area with an alchemy bench. The stone is on a shelf.',
    },
    {
        stoneId: 23,
        locationName: 'Yngvild',
        sublocationName: 'Yngvild Throne Room',
        holdName: 'Winterhold',
        stonePlacementDescription: 'Found on the desk in the last room, next to the final journal of Arondil.',
    },
]